### ISSUE TITLE
Provide installation instructions

### ISSUE THREAD

**Issue by cra0zy** [Ashark/archlinux-amdgpu#31]
Provide installation instructions or at least mention important information like downgrade to xorg 1.18. Making proper installation instructions might be better since most new arch users wouldn't know how to properly downgrade xorg.

**Comment by JontySR** [comment]
I second this. I only knew about the downgrade because I followed the last few days of the 16.60 thread, and even then, there were libraries that I had to replace to get 16.60 installed.

**Comment by corngood** [comment]
Yeah, good idea.  I'll at least add something to the AUR page.  Could you let me know which packages worked for you?

**Comment by JontySR** [comment]
@corngood I managed to install it when I downgraded xorg-server and xorg-common to 1.18.0-1, and in the same command xf86-input-libinput to 0.15.0-2 (and presumably any other xf86-* packages users have installed, as long as they are downgraded to the same/similar date to the xorg-server and xorg-server-common releases). They had to be downgraded in the same command due to cross-dependency I suppose. (I know you know that, but details)

I also had to install ncurses5-compat-libs, and to get around a PGP signature error, I used the method I outlined in #32 .

But then again, I have graphical glitches and @cra0zy had a build error, so it'd probably be wise to ask @nyorain who only had HDMI audio issues or @fjfalcon if they updated to 16.60.

**Comment by nyorain** [comment]
I only managed to install it thanks to @JontySR, had not known about the needed downgrade otherwise. So did everything the same way and it works (well, except hdmi audio which should work according to the [arch wiki](https://wiki.archlinux.org/index.php/AMDGPU#No_HDMI.2FDP_Audio)).

**Comment by JontySR** [comment]
Glad it helped, @nyorain any graphical issues?

**Comment by nyorain** [comment]
got the small purple border on the left of my display (but i think that is only related to amdgpu and pretty common) and chromium seems to have some issues with it like sometimes not rendering a page at all but other than that it's alright.

**Comment by Ashark** [comment]
ArchWiki lists needed packages to install. Closing stale issue.
