### ISSUE TITLE
License is not specified in the generated PKGBUILD

### ISSUE THREAD

**Issue by lahwaacz** [Ashark/archlinux-amdgpu#4]
The license should be specified in every PKGBUILD, but these generator scripts don't set it.
https://wiki.archlinux.org/index.php/PKGBUILD#license

It was previously set in https://aur.archlinux.org/cgit/aur.git/commit/?h=amdgpu-pro-installer&id=0ec049d64ecc41b5994ac612b994c1df344238e1
and removed later in https://aur.archlinux.org/cgit/aur.git/commit/?h=amdgpu-pro-installer&id=b9489951b2b01850cc7167b134bd626e8c7a6d6d

**Comment by corngood** [comment]
Thanks.  I put it back the way it was, in 22e03a0e87540927ee476c913c9b908372d9addd.

It's still techically not correct because the amd packages install the copyright notice in:
`/usr/share/doc/[pkgname]/` instead of `/usr/share/licenses/[pkgname]/`.

I'll leave the issue open until that gets sorted out.
