### ISSUE TITLE
Missing .deb files

### ISSUE THREAD

**Issue by BethAr** [Ashark/archlinux-amdgpu#57]
Hello,

I'm getting a validation check failure when installing and, if I skip validation, I get an error for missing `.deb` files. Should they be downloaded from AMD?

EDIT: Ok, it happens because the package refers to the 17.40 version which isn't available anymore.

EDIT2: I'm able to get it if I change the link in the PKGBUILD from `...amdgpu-pro-17.40-492261.tar.xz` to `...amdgpu-pro-17.40-514569.tar.xz`

**Comment by corngood** [comment]
Does it work ok?  I can update it if so.

**Comment by Tralen** [comment]
It worked for me. I don't know if every functionality is working properly, but it installs successfully. Besides the entries in the PKGBUILD, I had to replace the entries in the 0001 patch.

@BethAr, to build mesa-noglvnd I had to downgrade clang, llvm and llvm-libs. I downgraded to version 4.0.1-3, because I had it cached.

**Comment by BethAr** [comment]
Do I also need to downgrade Xorg?

**Comment by BethAr** [comment]
Ok, things are not working properly. I can't detect OpenGL:
```
$ glxinfo
name of display: :0.0
Error: couldn't find RGB GLX visual or fbconfig
```

**Comment by Tralen** [comment]
Downgrading llvm like I suggested to build mesa-noglvnd is the issue. It looks for a library for llvm 6. I'm still trying to figure a solution.
