### ISSUE TITLE
Help for installing

### ISSUE THREAD

**Issue by clintnetwork** [Ashark/archlinux-amdgpu#59]
Hello,

I'm currently trying to install archlinux and i've problem with gnome-shell apparently i must download the amdgpu-pro that is not covered by official amd, and you have made this package.

On the archlinux wiki i see that it's necessary to downgrade kernel and xorg, that's true ?

And can you make a little tuto or documentation for installing this package, i found that the problem of amdgpu-pro is a very big problem and amd does not maintain any package for other linux (only ubuntu and rhel are maintened)

Very thanks and sorry for my english, i'm french

**Comment by StripedMonkey** [comment]
gnome shell does not require amdgpu-pro.

**Comment by clintm90** [comment]
do you have an idea why i have gnome-shell at 60 or 70% ? i have seen that was due to the gpu driver... but i don't know

**Comment by znmeb** [comment]
The `amdgpu` driver is the way to go ... however ... how you make it work is highly dependent on the model of your AMD GPU!!!! It's taken a lot of reading of the Arch wiki page and a number of black screens before I got my "Bonaire" (Sea Islands) working. Some hints:

1. Know what family your card is. If it's older than Southern Islands, you need the `radeon` kernel module; if it's Southern Islands or later, the `amdgpu` kernel module.
2. The `amdgpu` kernel module is changing rapidly to catch up with AMD's rather rapid hardware releases. Phoronix is tracking this - <https://www.phoronix.com/scan.php?page=search&q=AMDGPU>. So every time the kernel updates, you'll probably have to fiddle with your kernel command line parameters.

**Comment by znmeb** [comment]
@corngood There's also a flag `amdgpu.dc=1` but that seems to make my Sea Island card unhappy.

**Comment by karroffel** [comment]
I see that the repo itself has not seen any changes since last year, I was wondering if there are plans to update this package for newer versions?

I also strongly agree that the opensource stack should be used whenever possible. Unfortunately, I am in need of a Vulkan profiling tool, and the Radeon GPU Profiler is the only available tool for me right now - which requires the use of the proprietary driver!

If this repo is no longer worked on really, are there other efforts of bringing amdgpu-pro to Arch?

**Comment by Ashark** [comment]
I have uploaded 19.20 version to AUR, closing.

**Comment by clintnetwork** [comment]
@corngood I have a ryzen 7
